PROJECT_NAME: ${PROJECT_NAME}
VERSION: ${VERSION}
API_V1_STR: ${API_V1_STR}
DB_USER: ${DB_USER}
DB_PASSWORD: ${DB_PASSWORD}
DB_HOST: ${DB_HOST}
DB_PORT: ${DB_PORT}
DB_NAME: ${DB_NAME}
DB_POOL_SIZE: ${DB_POOL_SIZE}
DB_MAX_OVERFLOW: ${DB_MAX_OVERFLOW}
DB_POOL_TIMEOUT: ${DB_POOL_TIMEOUT}
FRONTEND_HOST: ${FRONTEND_HOST}